### ISSUE TITLE
Replace `undefined` with `Not implemented`

### ISSUE THREAD

**Issue by dixonary** [samcoy3/advent-of-code-template#1]
The skeleton code contains stubs for parsers and part-days:

```haskell
------------ PART A ------------
partA :: Input -> OutputA
partA = undefined
```

It would be prudent to replace these with a more explicit error:

```haskell
------------ PART A ------------
partA :: Input -> OutputA
partA = error "Not implemented yet!"
```

[This is a change that hlint recommends, and a stopped clock is right twice a day]

**Comment by samcoy3** [comment]
[Done.](https://github.com/samcoy3/advent-of-code-template/commit/a80585cc4e45a17a6c950c6fcfec93a07ec144fb)
