### ISSUE TITLE
Include the `parser-combinators` library by default

### ISSUE THREAD

**Issue by dixonary** [samcoy3/advent-of-code-template#2]
Some critical tools have been factored out from the `attoparsec` library into the more generic `parser-combinators` library.

This includes `many`, a common combinator for getting zero or more instances of some parser.

It would be convienient if this library were a dependency by default, since lots of standard parsers will rely on it. (the attoparsec library does not make this effective-dependency clear)

**Comment by samcoy3** [comment]
[Done.](https://github.com/samcoy3/advent-of-code-template/commit/be8c52f1e87e772191481db7a305262d46b2a3e0)
